---
development:
  cloud_name: dtglppcio
  api_key: '484181593376451'
  api_secret: wPEibW-zI4dmQVoZaTCf260ruCs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dtglppcio
  api_key: '484181593376451'
  api_secret: wPEibW-zI4dmQVoZaTCf260ruCs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dtglppcio
  api_key: '484181593376451'
  api_secret: wPEibW-zI4dmQVoZaTCf260ruCs
  enhance_image_tag: true
  static_image_support: false
